"""Initial migration

Revision ID: 978a8608a461
Revises:
Create Date: 2021-03-13 17:28:34.673970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978a8608a461'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('environment', sa.String(), nullable=True),
                    sa.Column('weather', sa.String(), nullable=True),
                    sa.Column('differentiator', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('succulents',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('family_id', sa.Integer(), nullable=True),
                    sa.Column('life_time', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['family_id'], ['families.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('succulents')
    op.drop_table('families')
    # ### end Alembic commands ###
